version: '3'
services:
  etl:
    image: python:3.7-buster
    container_name: etl
    build: .
    volumes:
      - ./app:/app
      - ./data:/data
    ports:
      - 5000:5000

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
