version: '3'
services:
  etl:
    image: python:3.7-buster
    container_name: etl
    restart: always
    build: .
    links:
      - mongo
      - postgres
    volumes:
      - .:/app
      - ./data:/data
    ports:
      - 5000:5000

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432