version: '3'
services:
  etl:
    image: etl
    container_name: etl
    restart: always
    build: .
    volumes:
      - registry-volume:/app/registry
    ports:
      - 5000:5000

volumes:
  registry-volume: